import 'dart:async';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:mapbox_maps_flutter/mapbox_maps_flutter.dart';
import 'package:geolocator/geolocator.dart' as geo;
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:firebase_storage/firebase_storage.dart';
// ignore: library_prefixes
import 'package:cloud_firestore/cloud_firestore.dart' as firestore;
import 'package:google_nav_bar/google_nav_bar.dart';
import 'package:image_picker/image_picker.dart';
import 'package:table_calendar/table_calendar.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// ##################################################################
// #
// # ФАЙЛ: lib/firebase_options.dart
// #
// ##################################################################

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

/// Конфигурация на Firebase опции за различни платформи
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

// Конфигурация за уеб платформа
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwWl7_jErbyow_Uh88bJc7VJYLa8_ql9c',
    appId: '1:188912651305:web:00c4899a35ef61b3fc2038',
    messagingSenderId: '188912651305',
    projectId: 'zoodle-be9c3',
    authDomain: 'zoodle-be9c3.firebaseapp.com',
    storageBucket: 'zoodle-be9c3.firebasestorage.app',
    measurementId: 'G-8WKQZ429QJ',
  );

// Конфигурация за Android платформа
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMHegbi0SkMma_elgtkWnB3C9hZmJQf5U',
    appId: '1:188912651305:android:70e9bebe1714745afc2038',
    messagingSenderId: '188912651305',
    projectId: 'zoodle-be9c3',
    storageBucket: 'zoodle-be9c3.firebasestorage.app',
  );

// Конфигурация за iOS платформа
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC9i9vH-m5QLRZb6KGaRq_ro1U7NG-nsQ',
    appId: '1:188912651305:ios:80a357b56e85e9d5fc2038',
    messagingSenderId: '188912651305',
    projectId: 'zoodle-be9c3',
    storageBucket: 'zoodle-be9c3.firebasestorage.app',
    iosBundleId: 'com.example.animalRescueApp',
  );
}
